### PR TITLE
added container persistence presentation to accreditation

### PR DESCRIPTION
**Pull request by kacole2**
added the reaveal.js presentation for container persistence. click on the the index.html file to get started

Signed-off-by: Kendrick Coleman <kendrickcoleman@gmail.com>

### CODE REVIEW

**Comment by mcowger** [comment]
Couple items:

1.  Why does the license file mention 'Hakim El Hattab'?  Also, shouldn't this be the standard EMC MPL?

2. Is there anyway to avoid including all of the CSS/theme/HTML source in the repo?  Can it be pulled from the web on demand as a submodule or http reference?

**Comment by kacole2** [comment]
Hakim, was the creator of reveal.js. 

Jonas asked me to put the presentation in there. That's the entire presentation framework with everything included. I don't have the time to rip it apart just so we commit fewer files. 

We can reject it and just put a link to http://bit.ly/ContainerCon where the presentation is hosted.

**Comment by mcowger** [comment]
I'll leave it to @jonasrosland to reject or accept, but I would at least like to see the LICENSE file reflect reality (that some of this is Hakim's work, and some is yours).

Also I get a 404 on that bitly link.

**Comment by kacole2** [comment]
Lowercase c

http://bit.ly/containercon

**Comment by jonasrosland** [comment]
Fixed with PR #25, closing.

**Pull request closed without merging**
